# Usar uma imagem base do Python
FROM python:3.12-slim

# Definir o diretório de trabalho no container
WORKDIR /src

# Instalar dependências do sistema
RUN apt-get update && apt-get install -y \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Copiar o arquivo de requisitos e instalar as dependências do Django
COPY requirements.txt /src/

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

ARG TORQUE_USER
ARG TORQUE_HOME

RUN echo "${TORQUE_USER} ALL=(ALL) NOPASSWD: ${TORQUE_HOME}/sbin/trqauthd" >> /etc/sudoers

# Copiar o código do projeto para o container
COPY . /src/