# Generated by Django 5.0.7 on 2024-08-11 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0005_labsoa_smiles_bingo_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemical",
            name="chem_depiction_image",
            field=models.ImageField(null=True, upload_to="depictions/"),
        ),
        migrations.AlterField(
            model_name="chemical",
            name="literature",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chemicals.literature",
            ),
        ),
    ]
